import type { Metadata } from "next";
import { SanityLive } from "@/sanity/lib/live";
import "../../app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white text-black">
      <body>
        {children} <SanityLive />
      </body>
    </html>
  );
}
